# This is a basic workflow to help you get started with Actions

name: myworkflow

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]                # Trigger workflow when pushing to main branch
  pull_request:
    branches: [ "main" ]                # Trigger when a pull request is made to develop branch
  schedule:
    - cron: '0 0 * * 1'            # Trigger every Monday (minutes, hours, day of month, month, day of week)
  release:
    types: [published]                  # New release published
  issue_comment:
    types: [created, edited, deleted]   # Trigger on comment created, edited, or deleted
  delete:
    branches:                           # Trigger only when a branch is deleted
      - 'feature/*'                     # All branches starting with 'feature/'

  workflow_dispatch:                    # Allow manual triggering of the workflow
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test 1
        run: echo This is unit testing.
      - name: Test 2
        run: echo This is code format testing.
  deploy:
     runs-on: ubuntu-latest
     steps:
      - name: Deploy to Production
        run: echo Deploying to production server...
